In [15]:
# Import PyTorch library
import torch


In [16]:
# Create a 2D tensor
tensor = torch.tensor([[1, 2], [3, 4]])
print(tensor)

tensor([[1, 2],
        [3, 4]])


In [17]:
tensor

tensor([[1, 2],
        [3, 4]])

In [18]:
# Basic tensor operations
tensor_add = tensor + tensor
tensor_mul = tensor * tensor
tensor_matmul = torch.matmul(tensor, tensor)

print("Addition:\n", tensor_add)
print("Element-wise Multiplication:\n", tensor_mul)
print("Matrix Multiplication:\n", tensor_matmul)


Addition:
 tensor([[2, 4],
        [6, 8]])
Element-wise Multiplication:
 tensor([[ 1,  4],
        [ 9, 16]])
Matrix Multiplication:
 tensor([[ 7, 10],
        [15, 22]])


In [19]:
# Enable gradient tracking
x = torch.tensor(2.0, requires_grad=True)

y = x**2

# Compute gradients
y.backward()

# Access and print the gradient
print("Gradient of y with respect to x:", x.grad)

Gradient of y with respect to x: tensor(4.)


In [20]:
from torch.utils.data import Dataset, DataLoader
import pandas as pd


# Generating a simple example dataset dataframe
data = {
    "feature1": [0.5, 1.5, 2.5, 3.5, 4.5, 6.0],
    "feature2": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
    "feature3": [1.5, 2.5, 3.5, 4.5, 5.5, 7.0],
    "target": [2.0, 3.0, 4.0, 5.0, 6.0, 7.0]
}

df = pd.DataFrame(data)

# Dataset
class CustomDataset(Dataset):
    def __init__(self, dataframe):
        self.dataframe = dataframe
        self.features = dataframe.drop("target", axis=1).values
        self.targets = dataframe["target"].values

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        features = torch.tensor(self.features[idx], dtype=torch.float32)
        target = torch.tensor(self.targets[idx], dtype=torch.float32)
        return features, target

# Create an instance of the dataset
dataset = CustomDataset(df)
print(f"The dataset has {len(dataset)} samples")


# Dataloader
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

# Checking one batch of the dataloader
dataiter = iter(dataloader)
sample_X, sample_y = next(dataiter)
print(f"\n\nSample batch: \n\nX: {sample_X} \n\nY: {sample_y}")


The dataset has 6 samples


Sample batch: 

X: tensor([[0.5000, 1.0000, 1.5000],
        [3.5000, 4.0000, 4.5000]]) 

Y: tensor([2., 5.])


In [21]:
import torch.nn as nn

# Define a simple neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        # Declaring the layers to use
        self.fc1 = nn.Linear(3, 2)
        self.fc2 = nn.Linear(2, 1)
        self.relu = nn.ReLU()

    def forward(self, x):
        # Defining the connections and data flow across layers in the model
        # (2 inputs, 4 hidden neurons + ReLu, 1 output target)
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

# Instantiate the network
model = SimpleNN()
print(model)


SimpleNN(
  (fc1): Linear(in_features=3, out_features=2, bias=True)
  (fc2): Linear(in_features=2, out_features=1, bias=True)
  (relu): ReLU()
)


In [22]:
import torch.optim as optim

# Defining a Loss Function, we use the Mean Squared Error in this case
criterion = nn.MSELoss()

# Defining an Optimizer function, we use Stochastic Gradient Descent
optimizer = optim.SGD(model.parameters(), lr=0.005)



In [23]:
# Training loop
for epoch in range(10):
    print(f"---- Epoch {epoch+1} ----")
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        optimizer.zero_grad()  # Zero the gradients
        outputs = model(X).squeeze()  # Forward pass
        loss = criterion(outputs, y)  # Compute loss
        loss.backward()  # Backward pass
        optimizer.step()  # Update weights

        print(f"Batch {batch+1}, Loss: {loss}")    

---- Epoch 1 ----
Batch 1, Loss: 7.4690046310424805
Batch 2, Loss: 17.65382194519043
Batch 3, Loss: 26.777929306030273
---- Epoch 2 ----
Batch 1, Loss: 6.661708831787109
Batch 2, Loss: 7.172825813293457
Batch 3, Loss: 18.06693458557129
---- Epoch 3 ----
Batch 1, Loss: 3.8117458820343018
Batch 2, Loss: 1.2558903694152832
Batch 3, Loss: 0.6197564601898193
---- Epoch 4 ----
Batch 1, Loss: 0.1321382224559784
Batch 2, Loss: 0.10426364839076996
Batch 3, Loss: 0.071308434009552
---- Epoch 5 ----
Batch 1, Loss: 0.013189473189413548
Batch 2, Loss: 0.24772098660469055
Batch 3, Loss: 0.12977713346481323
---- Epoch 6 ----
Batch 1, Loss: 0.10149131715297699
Batch 2, Loss: 0.031407617032527924
Batch 3, Loss: 0.22959811985492706
---- Epoch 7 ----
Batch 1, Loss: 0.12110497057437897
Batch 2, Loss: 0.0742880254983902
Batch 3, Loss: 0.1561034917831421
---- Epoch 8 ----
Batch 1, Loss: 0.13337978720664978
Batch 2, Loss: 0.19584670662879944
Batch 3, Loss: 0.12535583972930908
---- Epoch 9 ----
Batch 1, Loss:

In [24]:
torch.cuda.is_available()


True

In [25]:
torch.cuda.device_count()


1

In [26]:
torch.cuda.get_device_name(0)


'NVIDIA GeForce RTX 2080 Ti'

In [27]:
# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Creating a new sample 
new_X = torch.tensor([2., 3., 3.])

# Move tensor to GPU
new_X = new_X.to(device)
print("New sample:", new_X)

# Move model to GPU
model = model.to(device)

# Inference from GPU
model.eval()
with torch.no_grad():
    pred = model(new_X)
    
print("Prediction:", pred[0])


Using device: cuda
New sample: tensor([2., 3., 3.], device='cuda:0')
Prediction: tensor(3.1465, device='cuda:0')


In [29]:
# Save the model as a compressed file
torch.save(model.state_dict(), "simple_nn.pth")

# Load the model
loaded_model = SimpleNN()
loaded_model.load_state_dict(torch.load("simple_nn.pth"))
print("Model loaded successfully\n")

loaded_model.to(device)

# Use the model to infer new samples
new_X = torch.tensor([4., 4.5, 5.], dtype=torch.float32)
new_X = new_X.to(device)

with torch.no_grad():
    pred = loaded_model(new_X)
    
print("Prediction:", pred)


Model loaded successfully

Prediction: tensor([5.2236], device='cuda:0')


C:\Users\alomg\AppData\Local\Temp\ipykernel_18200\1619593817.py:6: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded_model.load_state_dict(torch.load("simple_nn.pth"))
